[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Finch = "9177782c-1635-4eb9-9bfb-d9dfa25e6bce"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MatrixDepot = "b51810bb-c9f3-55da-ae3c-350fc1fbce05"
TensorMarket = "8b7d4fe7-0b45-4d0d-9dd8-5cc9b23b4b77"
